name: CD
on:
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Read Version
        id: version
        run: echo "version=$(dotnet versionize inspect)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com/saveapis
          username: ${{ secrets.DIGITALOCEAN_REGISTRY_USER }}
          password: ${{ secrets.DIGITALOCEAN_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          push: true
          context: .
          file: ./Bot/Dockerfile
          tags: |
            registry.digitalocean.com/saveapis/spotifyupdatebot:${{ steps.version.outputs.version }}